name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
          matrix:
            php: [5.5, 5.6]
    
    name: PHP ${{ matrix.php }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
          php-version: ${{ matrix.php }}

    - name: Run PHPUnit with Coverage
      run: phpunit --coverage-clover=coverage.clover

    - name: Get Scrutinizer CI
      run: wget https://scrutinizer-ci.com/ocular.phar

    - name: Run Scrutinizer CI
      run: php ocular.phar code-coverage:upload --format=php-clover coverage.clover